Fix regex for Topic entity
eclipse/ditto-clients-golang pull request #24
Opened 2022-02-22 12:48 UTC by antoniyatrifonova

According the specification (https://www.eclipse.org/ditto/protocol-specification-topic.html#messages-criterion-actions) for messages creation, the action segment can be freely chosen.

Signed-off-by: Antonia Trifonova antonia.trifonova@bosch.io

2022-02-22 12:48 UTC, antoniyatrifonova commented
@konstantina-gramatova please review this PR

2022-02-23 06:56 UTC, konstantina-gramatova requested changes

2022-02-23 06:56 UTC, konstantina-gramatova commented on protocol/topic.go
> +var regexSixElementTopic = regexp.MustCompile("^([^/]+)/([^/]+)/([^/]+)/([^/]+)/([^/]+)/(.*)$")
Can we simplify the regexp. here and replace the two separate ones with only one - something like e.g. `"^([^/]+)/([^/]+)/([^/]+)/([^/]+)/([^/]+)(/([^/]{1}.+))?$"` 
?
It's not a strict required RFC matcher but it's a start :)
That way only one regexp will be compiled and useful in both cases as well as helpful to simplify the logic using it.

2022-02-23 06:56 UTC, konstantina-gramatova commented on protocol/topic.go
>  	}
If only one regexp. is used - the logic here can be simplified (i.e. omit manual string splitting and concatenating) and rely on the matching groups in the regexp.
Please, see - func (*Regexp) [FindAllStringSubmatch](https://cs.opensource.google/go/go/+/go1.17.7:src/regexp/regexp.go;l=1190)

2022-02-24 08:24 UTC, konstantina-gramatova commented on protocol/topic.go
>  	}
Do we really need this check? The size of `elements` will always be a fixed one and the last element will always be a "" if there's no match for it?

2022-02-25 08:54 UTC, konstantina-gramatova approved these changes
LGTM

2022-02-25 08:58 UTC, merged